events {}

http {
    #Список доверенных прокси
    geo $remote_addr $from_trusted_proxy {
        default        0;
        172.30.0.11/32 1;   # nginx1
        172.30.0.12/32 1;   # nginx2
        172.30.0.13/32 1;   # nginx3
    }
    #Сосед — nginx: доверяем цепочке и дописываем свой адрес, сосед — пользователь: игнорируем его XFF
    map $from_trusted_proxy $xff_chain {
        1 "$http_x_forwarded_for, $server_addr";
        0 "$remote_addr, $server_addr";
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nginx2:80;
            proxy_set_header X-Forwarded-For $xff_chain;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}