events {}

http {
    map $remote_addr $clean_xff {
        default $remote_addr;
    }
    server {
        listen 80;

        location / {
            proxy_pass http://nginx2:80;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $clean_xff;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}